FROM jianfenghuang/gpu-jupyter:v1.14_cuda-11.6_ubuntu-20.04

RUN mkdir -p /home/jovyan/work/interim
RUN pip install effdet==0.2.4 albumentations==1.1.0 opencv-python==4.5.4.58 opencv-python-headless==4.5.4.58 timm==0.4.12 fastcore==1.3.27 ensemble-boxes==1.0.7
RUN pip install pytorch-lightning