apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: jupyter
      context: .
      custom:
        buildCommand: .staroid/build.sh
deploy:
  kubectl:
    manifests:
      - .staroid/k8s.yaml
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: .staroid/minikube.yaml
