version: "3.8"
services:
  gpu-container:
    build: .build
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    image: gpu-jupyter_test:1.1
    container_name: gpu_jupyter_container
    ports:
      - 8858:8888
    volumes:
      - ../../notebooks/:/home/jovyan/work/digf-coref/notebooks
      - ../../src/:/home/jovyan/work/digf-coref/src
      - ../../data/interim/:/home/jovyan/work/digf-coref/data/interim
      - ../../models/:/home/jovyan/work/digf-coref/models
      - /raid/nmis-ddm/coref-cv/data/raw/:/home/jovyan/work/digf-coref/data/raw
      - /raid/nmis-ddm/coref-cv/data/processed/:/home/jovyan/work/digf-coref/data/processed
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
    # enable sudo permissions
    user:
      "root"
    restart: always
