version: "3.8"
services:
  gpu-jupyter:
    container_name: gpu-jupyter
    build: .build
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    # # Set hardware limits: one GPU, max. 48GB RAM, max. 31 GPUs
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           device_ids: ["0"]  # select one GPU
    #     limits:
    #       cpus: "31.0"
    #       memory: 48g
    ports:
      - 8848:8888
    volumes:
      - ../../notebooks/:/home/jovyan/work/digf-coref/notebooks
      - ../../src/:/home/jovyan/work/digf-coref/src
      - ../../data/interim/:/home/jovyan/work/digf-coref/data/interim
      - ../../models/:/home/jovyan/work/digf-coref/models
      - /raid/nmis-ddm/coref-cv/data/raw/:/home/jovyan/work/digf-coref/data/raw
      - /raid/nmis-ddm/coref-cv/data/processed/:/home/jovyan/work/digf-coref/data/processed
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
    # enable sudo permissions
    user:
      "root"
    restart: always
